hyprdim: notify user that they can do this with stock Hyprland
hyprland-community/awesome-hyprland pull request #68
Opened 2024-03-19 14:16 UTC by holgerschurig

decoration {
    dim_inactive = true
    dim_strength = 0.4
}

2024-04-08 07:15 UTC, yavko requested changes
Sorry for the late response; could you also strike out the rest of the line `~~content other than the notice~~`

2024-04-16 03:01 UTC, yavko approved these changes

2024-04-16 03:01 UTC, merged

2024-04-23 02:34 UTC, MahouShoujoMivutilde commented
@yavko 

That doesn't actually replicate it.

`dim_inactive = true` just dims unfocused windows unconditionally, until they are focused.

Hyprdim dims windows _only_ when you're switching between them, they don't _stay_ dimmed, regaining their full brightness after 800ms (configurable).

It's right there in [features](https://github.com/donovanglover/hyprdim?tab=readme-ov-file#features):

>* Easily see which window has focus, even with subtle or no borders.
> * **Windows only dim when switching windows, eliminating the need to toggle dim on/off when you want to see other windows.**
> * Prevent windows from being dimmed if there are no other visible windows in a workspace.
> * Prevent windows from being dimmed when toggling special workspaces.
> * Dim background windows when dialog windows open.

2024-04-23 03:03 UTC, yavko commented
> @yavko
> 
> That doesn't actually replicate it.
> 
> `dim_inactive = true` just dims unfocused windows unconditionally, until they are focused.
> 
> Hyprdim dims windows _only_ when you're switching between them, they don't _stay_ dimmed, regaining their full brightness after 800ms (configurable).
> 
> It's right there in [features](https://github.com/donovanglover/hyprdim?tab=readme-ov-file#features):
> 
> > * Easily see which window has focus, even with subtle or no borders.
> > * **Windows only dim when switching windows, eliminating the need to toggle dim on/off when you want to see other windows.**
> > * Prevent windows from being dimmed if there are no other visible windows in a workspace.
> > * Prevent windows from being dimmed when toggling special workspaces.
> > * Dim background windows when dialog windows open.

i love it when people send false patches 😢