Added woomer, a Zomer app
hyprland-community/awesome-hyprland pull request #86
Opened 2024-05-27 09:35 UTC by diogomdp

2024-05-27 09:39 UTC, coffeeispower commented
I developed this application, it allows you to zoom your screen in and out, and also has a spotlight when you hold <kbd>CTRL</kbd>.
![woomer demo](https://github.com/coffeeispower/woomer/raw/main/demo.gif)

2024-06-16 00:27 UTC, yavko requested changes

2024-06-16 00:27 UTC, yavko commented on README.md
> +#### Zoomer application
This section name isn't the best, something like `Zooming utilities` would be better.

2024-06-16 00:27 UTC, yavko commented on README.md
> +- [woomer](https://github.com/coffeeispower/woomer) ![rust][rs] (Zoomer application for Wayland inspired by tsoding's boomer)
For the description, plz make it be `Zooming utility ....`

2024-06-16 00:58 UTC, BackHDLP commented on README.md
> +- [woomer](https://github.com/coffeeispower/woomer) ![rust][rs] (Zoomer application for Wayland inspired by tsoding's boomer)
reads like "Zoomer application — for Zoomers, by Zoomers" lol

2024-06-16 03:44 UTC, yavko commented on README.md
> +- [woomer](https://github.com/coffeeispower/woomer) ![rust][rs] (Zoomer application for Wayland inspired by tsoding's boomer)
fr fr

2024-06-16 07:05 UTC, coffeeispower commented on README.md
> +- [woomer](https://github.com/coffeeispower/woomer) ![rust][rs] (Zoomer application for Wayland inspired by tsoding's boomer)
That's the joke...

2024-06-16 13:39 UTC, diogomdp commented on README.md
> +- [woomer](https://github.com/coffeeispower/woomer) ![rust][rs] (Zoomer application for Wayland inspired by tsoding's boomer)
Fixed!

2024-06-16 19:10 UTC, yavko approved these changes

2024-06-16 19:10 UTC, merged