Add sys software suite
hyprland-community/awesome-hyprland pull request #87
Opened 2024-05-28 21:09 UTC by System64fumo

2024-06-15 19:31 UTC, System64fumo commented
@yavko

2024-06-16 00:18 UTC, yavko commented
> @yavko

i completely missed this sowwy

2024-06-16 00:19 UTC, System64fumo commented
All's good!

2024-06-16 00:20 UTC, yavko requested changes

2024-06-16 00:20 UTC, yavko commented on README.md
> +- [sysvol](https://github.com/System64fumo/sysvol) ![c++][cpp] (A basic GTK4 volume indicator)
why don't u stay consistent and have this also say gtkmm4

2024-06-16 00:20 UTC, yavko commented on README.md
> +- [sysmenu](https://github.com/System64fumo/sysmenu) ![c++][cpp] (A simple and efficient gtk4 program launcher)
here too

2024-06-16 00:20 UTC, System64fumo commented on README.md
> +- [sysvol](https://github.com/System64fumo/sysvol) ![c++][cpp] (A basic GTK4 volume indicator)
Honestly?
Fair point

2024-06-16 00:20 UTC, System64fumo commented on README.md
> +- [sysmenu](https://github.com/System64fumo/sysmenu) ![c++][cpp] (A simple and efficient gtk4 program launcher)
Very wel, ill change it

2024-06-16 00:23 UTC, System64fumo commented
Should be good now lmk

2024-06-16 00:24 UTC, yavko approved these changes

2024-06-16 00:24 UTC, yavko commented
aight sick

2024-06-16 00:24 UTC, merged

2024-06-16 00:25 UTC, System64fumo commented
Cool beans, Just as a heads up, sysvol will be renamed this week, likely in a few commits so uhh yeah keep ur heads up

2024-06-16 03:43 UTC, yavko commented
> Cool beans, Just as a heads up, sysvol will be renamed this week, likely in a few commits so uhh yeah keep ur heads up

oki, can u plz pr it then