Add hyprcursor and corrected capitialized cases
hyprland-community/awesome-hyprland pull request #89
Opened 2024-06-11 13:50 UTC by Heyian

I've added hyprcursor in the Tools/Official Tools section.

Also, hyprpaper and hyprpicker don't start with a capitalized "h" on the hyprwm repo.
So I changed it in the Tools/Official Tools section to reflect the original repo.

2024-06-11 22:30 UTC, yavko requested changes

2024-06-11 22:30 UTC, yavko commented on README.md
> +- [hyprcursor](https://github.com/hyprwm/hyprcursor) ![C++][cpp] (cursor utility)
This description is too vague

2024-06-13 17:59 UTC, Heyian commented on README.md
> +- [hyprcursor](https://github.com/hyprwm/hyprcursor) ![C++][cpp] (cursor utility)
@yavko there you go. I think that explains it better.

2024-06-16 00:24 UTC, yavko requested changes

2024-06-16 00:24 UTC, yavko commented on README.md
> +- [hyprcursor](https://github.com/hyprwm/hyprcursor) ![C++][cpp] (cursor format, library and utilities) **(XCursor replacement)**
I personally don't like this because readers of awesome-hyprland don't care that it's a library used in hyprland, the only thing that matters in this repo is the tools to make a cursor collection for hyprcursor. Also, the fact that it replaces xcursor is pretty irrelevant.
Something along the lines of: `(Utility for creating cursors for hyprland)` would be better imo

2024-06-16 19:07 UTC, Heyian commented on README.md
> +- [hyprcursor](https://github.com/hyprwm/hyprcursor) ![C++][cpp] (cursor format, library and utilities) **(XCursor replacement)**
I agree and I can't think of anything better. I'll push it shortly.

2024-06-16 19:10 UTC, yavko approved these changes

2024-06-16 19:11 UTC, merged